// <auto-generated />
namespace Tek4TV.Devices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Devices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Devices));
        
        string IMigrationMetadata.Id
        {
            get { return "202008270700249_Devices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
